### ISSUE TITLE
Problems training LORA

### ISSUE THREAD

**Issue by ldj0o** [GaussianObject/GaussianObject#18]
I put the .pth file and .ckpt file into the models folder in advance, but an error occurred when loading the .pth file. The following is the running log.

**Traceback (most recent call last):
File "/home/yxiong/Gaussian Object/GaussianObject/train_lora.py", line 52, in <module>
model.load_state_dict(load_state_dict(f'./models/{args.model_name}.pth', location='cpu'), strict=False)
File "/home/yxiong/Gaussian Object/GaussianObject/cldm/model.py", line 18, in load_state_dict
state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
File "/home/yxiong/anaconda3/envs/go/lib/python3.10/site-packages/torch/serialization.py", line 797, in load
with _open_zipfile_reader(opened_file) as opened_zipfile:
File "/home/yxiong/anaconda3/envs/go/lib/python3.10/site-packages/torch/serialization.py", line 283, in __init__
super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: invalid header or archive is corrupted**

**Comment by ldj0o** [comment]
I have downloaded the model again and it can run now
