### ISSUE TITLE
error when Coarse 3DGS step, return ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by SaiZyca** [GaussianObject/GaussianObject#33]
full log
---
```bash
Optimizing output/gs_init/kitchen
Listening on 127.0.0.1:6009 [30/05 12:20:34]
Output folder: output/gs_init/kitchen [30/05 12:20:34]
Using resized images in C:\_Dev\Repository\GaussianObject\data\mip360\kitchen\images_4... [30/05 12:20:35]
Reading camera 279/279 [30/05 12:20:41]
Generating ellipse path from 279 camera infos ... [30/05 12:20:41]
theta[0] 0.0 [30/05 12:20:41]
Sparse view, only 4 images are used for training, others are used for eval. [30/05 12:20:41]
Loading training cameras with 0.9519944190979004s [30/05 12:20:42]
Loading test cameras with 0.48201775550842285s [30/05 12:20:43]
Loading render cameras with 0.4770045280456543s [30/05 12:20:43]
Number of points at initialisation :  8616 [30/05 12:20:43]
Training progress:   0%|                                                                                                                                     | 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\_Dev\Repository\GaussianObject\train_gs.py", line 286, in <module>
    training(args, lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_Dev\Repository\GaussianObject\train_gs.py", line 86, in training
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_Dev\Repository\GaussianObject\gaussian_renderer\__init__.py", line 85, in render
    rendered_image, radii, rendered_depth, rendered_alpha = rasterizer(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 2)
Training progress:   0%|
```

**Comment by GaussianObject** [comment]
The `diff-gaussian-rasterization` module of the repo differs from the vanilla 3DGS to support depth and alpha rendering. You may need to reinstall the module from our submodules.
