### ISSUE TITLE
visual_hull.py error

### ISSUE THREAD

**Issue by TXSevenXT** [GaussianObject/GaussianObject#34]
Hi there!

Thank you very much for this great work :)

I haven't managed to take advantage of the code for my own data yet, but I'm planning to =D

I end up with the following error code at the “visual_hull.py” command:

(GO) xsevenx@PC:~/GaussianObject$ python visual_hull.py     --sparse_id 9     --data_dir "/home/xsevenx/segment-anything/data/Cascade_dense_02/"     --not_vis
Using resized images in /home/xsevenx/segment-anything/data/Cascade_dense_02/images...
Reading camera 29/29
Generating ellipse path from 29 camera infos ...
theta[0] 0.0
the sparse id is 9, with 9 frames
the camera center is: tensor([ 0.1372,  0.0131, -0.0067], device='cuda:0')
Traceback (most recent call last):
  File "/home/xsevenx/GaussianObject/visual_hull.py", line 223, in <module>
    pcd, bbox = get_visual_hull(args.voxel_num, init_bbox, scene_info, cam_center)
  File "/home/xsevenx/GaussianObject/visual_hull.py", line 85, in get_visual_hull
    new_masks.append(simple_resize_image(mask, img_size))
  File "/home/xsevenx/GaussianObject/visual_hull.py", line 66, in simple_resize_image
    return transforms.Resize(size, antialias=True)(img)
  File "/home/xsevenx/anaconda3/envs/GO/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/xsevenx/anaconda3/envs/GO/lib/python3.10/site-packages/torchvision/transforms/transforms.py", line 361, in forward
    return F.resize(img, self.size, self.interpolation, self.max_size, self.antialias)
  File "/home/xsevenx/anaconda3/envs/GO/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 476, in resize
    _, image_height, image_width = get_dimensions(img)
  File "/home/xsevenx/anaconda3/envs/GO/lib/python3.10/site-packages/torchvision/transforms/functional.py", line 78, in get_dimensions
    return F_pil.get_dimensions(img)
  File "/home/xsevenx/anaconda3/envs/GO/lib/python3.10/site-packages/torchvision/transforms/_functional_pil.py", line 31, in get_dimensions
    **raise TypeError(f"Unexpected type {type(img)}")
TypeError: Unexpected type <class 'NoneType'>**

I don't know if this has anything to do with the “sparse_9.txt” I created manually?

I couldn't find a way to output this txt file in an optimized and automatic way :(
If it's coming from there, what's the most appropriate way to output these files?

Thank you very much for your help and your time

XSevenX

**Comment by GaussianObject** [comment]
Thank you for your interest in our project!

The `sparse_9.txt` file you mentioned is supposed to contain the indices of images used for training, starting from 0. If your intention is to use all 29 cameras for your computation, you should set the `--sparse_id` to `29` with

```bash
python visual_hull.py --sparse_id 29 --data_dir "/home/xsevenx/segment-anything/data/Cascade_dense_02/" --not_vis
```

Additionally, you'll need to create a `sparse_29.txt` file in your data directory (`/home/xsevenx/segment-anything/data/Cascade_dense_02/`). This file should list the indices from 0 to 28 as

```txt
0
1
2
...
28
```

Let us know if this resolves your issue or if there's anything else we can help with!

**Comment by FanYaning** [comment]
应该是我没有生成masks文件夹导致的，get_visual_hull方法中 的masks = scene_info.masks，masks 值是None
masks is the object mask generated with [segment-anything](https://github.com/facebookresearch/segment-anything).

**Comment by HTLiu-AMS** [comment]
At dataset_readers.py line 110
Change "png" format to your own mask image format, for example, JPG
Maybe it works
