### ISSUE TITLE
Super slow LoRA Fine-Tuning with a GeForce RTX 3080 GPU!

### ISSUE THREAD

**Issue by MrForExample** [GaussianObject/GaussianObject#4]
Hi, I'm running this project on my laptop with a GeForce RTX 3080 GPU & Windows 11 OS, inside a miniconda environment with all the required packages and following your example command precisely.

From your paper's section 4 [EXPERIMENTS]:
> The whole process of GaussianObject takes about 30 minutes on a GeForce RTX 3090 GPU for 4 input images at a 779 × 520 resolution.

But I'm training for more than an hour in the **LoRA Fine-Tuning stage** already, and the progress is still working at: 
`Epoch 32:  25%|▎| 1/4 [00:24<01:12, 24.31s/it, loss=0.0371, v_num=0, train/loss_simple_step=0.029, train/loss_vlb_step=9.67e-5, train/loss_step=0.029, global_step=128.0`

Have I done something wrong? What I am missing that keeps me from running this project as fast as your experiment?

**Comment by GaussianObject** [comment]
Thank you for your feedback and kind words!

In the experiment settings described in the `README.md`, the LoRA Fine-Tuning stage requires approximately 14GB of GPU memory. This amount is manageable for an RTX 3090 with 24GB but may pose challenges for an RTX 3080 with 10GB / 12GB. This discrepancy is likely the main reason for the observed slow speed. I recommend monitoring your GPU memory usage to confirm if this assumption is accurate.

For devices with lower memory, it is advised to run the kitchen scene with a resolution factor of 8. Additionally, you'll need to adjust several parameters in both the LoRA Fine-Tuning stage and the Gaussian Repair stage as follows:

```sh
# LoRA Fine-Tuning stage
python train_lora.py --exp_name controlnet_finetune/kitchen \
    --prompt xxy5syt00 --sh_degree 2 --resolution 8 --sparse_num 4 \
    --data_dir data/mip360/kitchen \
    --gs_dir output/gs_init/kitchen \
    --loo_dir output/gs_init/kitchen_loo \
    --bg_white --sd_locked --train_lora --use_prompt_list \
    --add_diffusion_lora --add_control_lora --add_clip_lora \
    --image_size 256

# Gaussian Repair stage
python train_repair.py \
    --config configs/gaussian-object.yaml \
    --train --gpu 0 \
    tag="kitchen" \
    system.init_dreamer="output/gs_init/kitchen" \
    system.exp_name="output/controlnet_finetune/kitchen" \
    system.refresh_size=8 \
    data.data_dir="data/mip360/kitchen" \
    data.resolution=8 \
    data.sparse_num=4 \
    data.prompt="a photo of a xxy5syt00" \
    data.refresh_size=8 \
    system.sh_degree=2 \
    system.novel_image_size=256
```

and adjust the path rendering resolution with `image_size = 256` as we currently have not set an argument for it

https://github.com/GaussianObject/GaussianObject/blob/c087d48a551649fe30e2ed24a74eec80690b68ab/render.py#L246-L248

**Comment by MrForExample** [comment]
Thank you for your advice, I'll try again soon 👍

**Comment by MrForExample** [comment]
Hi friend, I tried it again, with all the modification you recommended, but it at best saves 10 to 20 seconds for each epoch, well then I guess it is really done to the GPU compute power & memory capacity.

![Screenshot 2024-02-22 113502](https://github.com/GaussianObject/GaussianObject/assets/62230687/93f2c714-a850-433f-a1db-80cb35732735)

Here is the snapshot:
```bash
(Wonder3D) C:\Users\reall\Softwares\Miniconda3\envs\Wonder3D\_Projects\GaussianObject>python train_lora.py --exp_name controlnet_finetune/kitchen --prompt xxy5syt00 --sh_degree 2 --resolution 8 --sparse_num 4 --data_dir data/mip360/kitchen --gs_dir output/gs_init/kitchen --loo_dir output/gs_init/kitchen_loo --bg_white --sd_locked --train_lora --use_prompt_list --add_diffusion_lora --add_control_lora --add_clip_lora --image_size 256
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\reall\Softwares\Miniconda3\envs\Wonder3D\Lib\site-packages\xformers\__init__.py", line 55, in _is_triton_available
    from xformers.triton.softmax import softmax as triton_softmax  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reall\Softwares\Miniconda3\envs\Wonder3D\Lib\site-packages\xformers\triton\softmax.py", line 11, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
ControlLDM: Running in eps-prediction mode
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Loaded model config from [./models/control_v11f1e_sd15_tile.yaml]
Loaded state_dict from [./models/v1-5-pruned.ckpt]
Loaded state_dict from [./models/control_v11f1e_sd15_tile.pth]
Using resized images in data/mip360/kitchen\images_8...
Load 25 images for leave 14
Load 25 images for leave 70
Load 25 images for leave 171
Load 25 images for leave 196
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
C:\Users\reall\Softwares\Miniconda3\envs\Wonder3D\Lib\site-packages\pytorch_lightning\trainer\configuration_validator.py:108: PossibleUserWarning: You defined a `validation_step` but have no `val_dataloader`. Skipping val loop.
  rank_zero_warn(
You are using a CUDA device ('NVIDIA GeForce RTX 3080 Laptop GPU') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type               | Params
---------------------------------------------------------
0 | model             | DiffusionWrapper   | 883 M
1 | first_stage_model | AutoencoderKL      | 83.7 M
2 | cond_stage_model  | FrozenCLIPEmbedder | 136 M
3 | control_model     | ControlNet         | 372 M
---------------------------------------------------------
1.3 B     Trainable params
206 M     Non-trainable params
1.5 B     Total params
5,905.375 Total estimated model params size (MB)
C:\Users\reall\Softwares\Miniconda3\envs\Wonder3D\Lib\site-packages\pytorch_lightning\trainer\connectors\data_connector.py:224: PossibleUserWarning: The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.
  rank_zero_warn(
C:\Users\reall\Softwares\Miniconda3\envs\Wonder3D\Lib\site-packages\pytorch_lightning\trainer\trainer.py:1609: PossibleUserWarning: The number of training batches (4) is smaller than the logging interval Trainer(log_every_n_steps=50). Set a lower value for log_every_n_steps if you want to see logs for the training epoch.
  rank_zero_warn(
Epoch 0:   0%|                                                                                                                                                      | 0/4 [00:00<?, ?it/s]C:\Users\reall\Softwares\Miniconda3\envs\Wonder3D\Lib\site-packages\pytorch_lightning\utilities\data.py:83: UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
  warning_cache.warn(
C:\Users\reall\Softwares\Miniconda3\envs\Wonder3D\Lib\site-packages\pytorch_lightning\trainer\connectors\logger_connector\result.py:234: UserWarning: You called `self.log('global_step', ...)` in your `training_step` but the value needs to be floating point. Converting it to torch.float32.
  warning_cache.warn(
Epoch 3:  25%|▎| 1/4 [00:23<01:10, 23.59s/it, loss=0.0596, v_num=2, train/loss_simple_step=0.00808, train/loss_vlb_step=3.57e-5, train/loss_step=0.00808, global_step=12.00, train/loss_si
```

**Comment by MrForExample** [comment]
No problem, thanks for clarification, have a good day 👍
