### ISSUE TITLE
the dimension of pre_status and cur_status NOT equal  in leave_one_out_stage2

### ISSUE THREAD

**Issue by husthzy** [GaussianObject/GaussianObject#70]
I trained with my own dataset.

python leave_one_out_stage2.py -s data/realcap/mario -m output/gs_init/mario_loo -r 8 --sparse_view_num 4 --sh_degree 2 --init_pcd_name dust3r_4 --dust3r_json output/gs_init/mario/refined_cams.json --white_background --random_background --use_dust3r

This is the error info:
`
[ITER 7000] Evaluating train: L1 0.005111759598366916 PSNR 30.6793571472168 [29/11 17:37:02]
Training progress: 100%|██████████████████████████████████████████████| 24000/24000 [04:38<00:00, 86.09it/s, Loss=0.0032718, n=29527]

[ITER 30000] Saving Gaussians [29/11 17:41:22]
key:_xyz [29/11 17:41:22]
pre_c shape:torch.Size([29667, 3]) [29/11 17:41:22]
cur_c shape:torch.Size([29527, 3]) [29/11 17:41:22]
Traceback (most recent call last):
  File "/home/code/GaussianObject/leave_one_out_stage2.py", line 328, in <module>
    train_3dgs(args, ids)
  File "/home/code/GaussianObject/leave_one_out_stage2.py", line 280, in train_3dgs
    leave_one_out_training(args,
  File "/home/code/GaussianObject/leave_one_out_stage2.py", line 136, in leave_one_out_training
    diff = pre_c - cur_c
RuntimeError: The size of tensor a (29667) must match the size of tensor b (29527) at non-singleton dimension 0
`

**Comment by 7rwang** [comment]
Fixed? Sometimes I will also encounter the same error

**Comment by husthzy** [comment]
> Fixed? Sometimes I will also encounter the same error

Not yet.  I am trying to reinstall the env

**Comment by husthzy** [comment]
set iterations = 10_000, it will be ok.
set iterations = 30_000, it will be error.

I have not know the reason.

**Comment by husthzy** [comment]
After carefully analyzing the code, I found that commenting out the diff code has no effect on model training. I am verifying this.

**Comment by 7rwang** [comment]
> set iterations = 10_000, it will be ok. set iterations = 30_000, it will be error.
> 
> I have not know the reason.

It's weird. Cuz from my perspective, prune is random, it's difficult to keep the number unchanged in two stages

**Comment by husthzy** [comment]
> > set iterations = 10_000, it will be ok. set iterations = 30_000, it will be error.
> > I have not know the reason.
> 
> It's weird. Cuz from my perspective, prune is random, it's difficult to keep the number unchanged in two stages

Since pruning will occur, why does the code directly subtract two statuses?

I added a check to force the dimensions to be consistent, and the training worked fine, but I can't confirm whether this is correct.

**Comment by UranusITS** [comment]
In the leave-one-out Stage 1, we save the 3DGS checkpoint using the checkpoint_iterations argument, which is fixed to 6000.

https://github.com/chensjtu/GaussianObject/blob/91048a5dd3f9313e5bca8ecca651bdbac5099836/leave_one_out_stage1.py#L304

In Stage 2, we directly load the checkpoint file, and this causes the unexpected issue when changing the number of iterations. Relevant sections:

https://github.com/chensjtu/GaussianObject/blob/91048a5dd3f9313e5bca8ecca651bdbac5099836/leave_one_out_stage2.py#L29

https://github.com/chensjtu/GaussianObject/blob/91048a5dd3f9313e5bca8ecca651bdbac5099836/leave_one_out_stage2.py#L275

Apologies for not fully considering the case when changing the number of iterations.

**Comment by chensjtu** [comment]
exactly
